services:
  wiki:
    build: .
    volumes:
      - ./data/images:/var/www/html/images
      # Extensions with customizations, others are copied on image build
      - ./extensions/PageForms:/var/www/html/extensions/PageForms
      - ./extensions/ConfirmEdit:/var/www/html/extensions/ConfirmEdit
      # Settings
      - ./conf/LocalSettings.php:/var/www/html/LocalSettings.php
      # Semantics Configuration
      - ./data/semantics:/var/www/html/semantics_config
      # Nginx configuration
      - ./conf/nginx.conf:/etc/nginx/sites-enabled/default
    ports:
      - "${WIKI_PORT}:80"
    environment:
      - WIKI_ENV=Dev
      - DB_TYPE=mysql
      - DB_SERVER=db
      - DB_NAME
      - DB_USER
      - DB_PASSWORD
      - ADMIN_USER
      - ADMIN_PASS
      - FULL_URL=http://localhost:${WIKI_PORT}
      - MEDIAWIKI_SECRET
      - WIKI_CAPTCHA_KEY
      - WIKI_CAPTCHA_SITE
  db:
    image: mariadb:10.6.13
    restart: always
    environment:
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
    volumes:
      - ./data/db:/var/lib/mysql
