version: 2
jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:27.0.3-cli
    steps:
      - checkout
      - run:
          name: init submodules
          command: |
            cd /app
            git submodule sync --recursive && git submodule update --recursive --init
            cd -
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache \
              pipx
            pipx install \
              awscli
      - restore_cache:
          keys:
            - v1-{{ .Branch }}
          paths:
            - /caches/app.tar
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/app.tar | true
      - run:
          name: Build application Docker image
          command: |
            docker build --cache-from=app -t app .
      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p /caches
            docker save -o /caches/app.tar app
      - save_cache:
          key: v1-{{ .Branch }}-{{ epoch }}
          paths:
            - /caches/app.tar
      - deploy:
          name: Push application Docker image
          command: |
            if [ "${CIRCLE_BRANCH}" == "main" ]; then
              /root/.local/bin/aws ecr get-login-password \
                  --region eu-central-1 \
                | docker login \
                    --username AWS \
                    --password-stdin 637025038750.dkr.ecr.eu-central-1.amazonaws.com
              docker tag app "${ECR_ENDPOINT}/wiki:${CIRCLE_SHA1}"
              docker tag app "${ECR_ENDPOINT}/wiki:latest"
              docker push "${ECR_ENDPOINT}/wiki:${CIRCLE_SHA1}"
              docker push "${ECR_ENDPOINT}/wiki:latest"

            fi