blank_issues_enabled: false
contact_links:
  - name: Using the wiki? Report it here
    url: https://github.com/repair-wiki/wiki-issues/issues
    about: For reporting anything wrong with the wiki.
  - name: Security vulnerability
    url: mailto:team@repair.wiki
    about: Please report security issues privately via email, not as a public issue.
  - name: Discord
    url: https://discord.gg/7y9NP39k4C
    about: For general chat, and suggesting wiki content.
